# Site settings
title: System-on-Chip Design & Verification
author: Anesu Njove
  name: Anesu Njove
  email: g00425238@atu.ie
description: "FPGA Project"

# Build settings
remote_theme: jekyll/minima
